# Site settings
title: Alex Blog
SEOTitle: Alex blog
header-img: img/home-bg.jpg
email: alexzzhe@gmail.com
description: "Alex blog"
keyword: "Alex blog"
url: ""              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     _Alex_He
#zhihu_username:     alexzZhe
github_username:    alexzZhe



# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

#gems
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Dev Ops"
sidebar-avatar: /img/sidebar-avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

duoshuo_share: 
#duoshuo_username: 

# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



